### ISSUE TITLE
All elements moves when hover over "day X" div on blog page.

### ISSUE THREAD

**Issue by Harshal-Gahlot** [aryaidnani/aryaidnani#1]
On the blog page, when we hover over any day element, all the elements below it also move which makes the website uncool.

I have solved the issue locally. Ready to merge and contribute.
Identifying the problem is easy and there are multiple solutions.
I just went with the simplest one which only requires adding a couple of words.

**Comment by aryaidnani** [comment]
Thanks for the feedback!
I have solved the issue by setting the line height of super tag to 0 and it seems to work.
Will push the css changes with tomorrow's blog.
Appreciated!!
